---
abstract: 'rewrite HTML5+Microdata into XHTML+RDFa'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-HTML5-Microdata-ToRDFa
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.00
  DateTime: 0
  RDF::Trine: 0.112
  URI: 1.30
  XML::LibXML: 1.60
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Microdata-ToRDFa
  homepage: http://search.cpan.org/dist/HTML-HTML5-Microdata-ToRDFa/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/HTML-HTML5-Microdata-ToRDFa/
version: 0.01
