---
abstract: 'rewrite HTML5+Microdata into XHTML+RDFa'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::HTML5::Microdata::ToRDFa
name: HTML-HTML5-Microdata-ToRDFa
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  HTML::HTML5::Microdata::Parser: 0.100
  HTML::HTML5::Writer: 0
  RDF::Prefixes: 0.002
  Scalar::Util: 0
  XML::LibXML: 1.70
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Microdata-ToRDFa
  homepage: https://metacpan.org/release/HTML-HTML5-Microdata-ToRDFa
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/HTML-HTML5-Microdata-ToRDFa/
version: 0.100
